from sqlalchemy import Column, Integer, String, Date
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    password = Column(String)
    avatar_url = Column(String, nullable=True)

class Player(Base):
    __tablename__ = "players"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    full_name = Column(String, nullable=False)
    birth_date = Column(Date, nullable=False)
    age = Column(Integer, nullable=False)
    height_cm = Column(Integer, nullable=False)
    weight_kgs = Column(Integer, nullable=False)
    positions = Column(String, nullable=False)
    nationality = Column(String, nullable=False)
    overall_rating = Column(Integer, nullable=False)
    potential = Column(Integer, nullable=False)
    value_euro = Column(Integer, nullable=False)
    wage_euro = Column(Integer, nullable=False)
    preferred_foot = Column(String, nullable=False)
    international_reputation = Column(Integer, nullable=False)
    weak_foot = Column(Integer, nullable=False)
    skill_moves = Column(Integer, nullable=False)
    body_type = Column(String, nullable=False)
    release_clause_euro = Column(Integer, nullable=False)
    national_team = Column(String, nullable=True)
    national_rating = Column(Integer, nullable=True)
    national_team_position = Column(String, nullable=True)
    national_jersey_number = Column(Integer, nullable=True)
    crossing = Column(Integer, nullable=False)
    finishing = Column(Integer, nullable=False)
    heading_accuracy = Column(Integer, nullable=False)
    short_passing = Column(Integer, nullable=False)
    volleys = Column(Integer, nullable=False)
    dribbling = Column(Integer, nullable=False)
    curve = Column(Integer, nullable=False)
    freekick_accuracy = Column(Integer, nullable=False)
    long_passing = Column(Integer, nullable=False)
    ball_control = Column(Integer, nullable=False)
    acceleration = Column(Integer, nullable=False)
    sprint_speed = Column(Integer, nullable=False)
    agility = Column(Integer, nullable=False)
    reactions = Column(Integer, nullable=False)
    balance = Column(Integer, nullable=False)
    shot_power = Column(Integer, nullable=False)
    jumping = Column(Integer, nullable=False)
    stamina = Column(Integer, nullable=False)
    strength = Column(Integer, nullable=False)
    long_shots = Column(Integer, nullable=False)
    aggression = Column(Integer, nullable=False)
    interceptions = Column(Integer, nullable=False)
    positioning = Column(Integer, nullable=False)
    vision = Column(Integer, nullable=False)
    penalties = Column(Integer, nullable=False)
    composure = Column(Integer, nullable=False)
    marking = Column(Integer, nullable=False)
    standing_tackle = Column(Integer, nullable=False)
    sliding_tackle = Column(Integer, nullable=False)